name: "vzlogger for homeassistant"
version: "1.0.3"
slug: "homeassistant-addon-vzlogger"
# devices:
#  - /dev/ttyUSB0
description: "vzlogger for homeassistant to log meter"
url: "https://github.com/unl0ck/homeassistant-addon-vzlogger.git"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
apparmor: false
privileged: ["SYS_RAWIO"]
map:
  - share:ro
schema:
  configfile: "str"
  device: device(subsystem=tty)
options:
  device: null
  configfile": /share/vzlogger.conf
ports:
  8084/tcp: 8084
ports_description:
  8084/tcp: REST interface
init: false
image: ghcr.io/unl0ck/homeassistant-addon-vzlogger-{arch}
timeout: 30
